### ISSUE TITLE
Expected `onClick` listener to be a function, instead got a value of `object` type.

### ISSUE THREAD

**Issue by prathamsakhare** [prathamsakhare/onedsaonemail#1]
I am getting this error When I am trying to call a function that use fetch in next.js
here is code -- 

          "use client";
          import React, { useState } from "react";
          const Email = () => {
              async function handleSubmit(e){
                  // e.preventDefault();
                  await fetch('api/email', {
                      method : 'GET',
                      body : JSON.stringify({
                          firstName : "Cosmo"
                      })
                  })
              }
            return (
              <div className="flex flex-col `items-center` justify-center min-h-screen py-2">
                  <button onClick={handleSubmit()}>Send Email</button>
              </div>
            );
          };
          export default Email;
![image](https://github.com/prathamsakhare/onedsaonemail/assets/100476513/85e716fe-7e1f-4afe-9236-690ea0ab24b4)

**Comment by hashiq300** [comment]
Security Reminder: It's important to be aware of a security threat in the code. Specifically, avoid pushing sensitive .env variables to public repositories. These variables may contain confidential information such as API keys or database credentials, and exposing them publicly can lead to potential security breaches. Always ensure that such sensitive data remains protected and is not accessible to unauthorized users.

add .env in gitignore file
